version: "3.7"

services:

  application:
    build: .
    restart: always
    ports:
      - 8080:8080
    env_file:
      - application.env
    networks:
      - back-network

networks:
  back-network:
